# runtime requirements
MIN_CONTAINERD_VERSION="1.7.24"
MIN_RUNC_VERSION="1.1.5"

# dependencies
FINCHD_RELEASE="0.23.3"
FINCHD_COMMIT=""
NERDCTL_RELEASE=""
NERDCTL_COMMIT=""
BUILDKIT_RELEASE=""
BUILDKIT_COMMIT=""
SOCI_RELEASE=""
SOCI_COMMIT=""
CNI_RELEASE=""
CNI_COMMIT=""
COSIGN_RELEASE="3.0.5"
COSIGN_COMMIT="479147a4df05f31be48aeb2b3a9d32dfc35ba877"
